language: scala
sudo: false
jdk:
  - oraclejdk8

scala:
  - 2.12.8

script:
  - sbt                     clean filesJVM/coverageTest concurrent-x/coverageTest
  - sbt -Dcoveralls.disable       filesJS/test

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"
    - "$HOME/.zinc"
    - "$HOME/.coursier"

after_success:
  # work around https://github.com/codecov/codecov-bash/issues/133
  - curl -s https://codecov.io/bash > .codecov
  - sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
  - chmod +x .codecov
  - ./.codecov

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install request jsdom
  - node --version
